export const WEATHER_REQUEST = 'WEATHER/WEATHER_REQUEST'
export const WEATHER_REQUEST_SUCCESS = 'WEATHER/WEATHER_REQUEST_SUCCESS'
export const WEATHER_REQUEST_FAILED = 'WEATHER/WEATHER_REQUEST_FAILED'

export const UPDATE_INDICATORS = 'WEATHER/UPDATE_INDICATORS'

export const CHANGE_PHASE = 'WEATHER/CHANGE_PHASE'